//---------------Drawer ACTIONS
export const TOGGLE_DRAWER = 'APP_CONFIG/TOGGLE_DRAWER'
export const RESET_RIGHT_DRAWER = 'APP_CONFIG/RESET_RIGHT_DRAWER'
export const OPEN_RIGHT_DRAWER = 'APP_CONFIG/OPEN_RIGHT_DRAWER'

//-----------User Auth Actions
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE'

export const SET_PROFILE_DATA = 'SET_PROFILE_DATA'

export const PRODUCT_FETCHING_SUCCESS = 'PRODUCT_FETCHING_SUCCESS'
export const PRODUCT_FETCHING_FAILURE = 'PRODUCT_FETCHING_FAILURE'