//---------------Drawer ACTIONS
export const TOGGLE_DRAWER = 'APP_CONFIG/TOGGLE_DRAWER'
export const RESET_RIGHT_DRAWER = 'APP_CONFIG/RESET_RIGHT_DRAWER'
export const OPEN_RIGHT_DRAWER = 'APP_CONFIG/OPEN_RIGHT_DRAWER'

//-----------User Auth Actions
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE'

export const SET_PROFILE_DATA = 'SET_PROFILE_DATA'

export const PRODUCT_FETCHING_SUCCESS = 'PRODUCT_FETCHING_SUCCESS'
export const PRODUCT_FETCHING_FAILURE = 'PRODUCT_FETCHING_FAILURE'
export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const SET_CARD_NAME = 'SET_CARD_NAME'

export const GET_CART = 'GET_CART'
export const EDIT_CART_SUCCESS = 'EDIT_CART_SUCCESS'
export const EDIT_CART_FAILURE = 'EDIT_CART_FAILURE'
export const TOGGLE_CART = 'TOGGLE_CART'
export const SET_CART_TO_INITIAL = 'SET_CART_TO_INITIAL'
export const TOGGLE_CART_UNANOMOUSLY = 'TOGGLE_CART_UNANOMOUSLY'
export const TOTAL_AMOUNT = 'TOTAL_AMOUNT'
export const QUANTITY_CHANGE = 'QUANTITY_CHANGE'

export const SET_IS_ORDER_IN_PLACE = 'SET_IS_ORDER_IN_PLACE'
export const SET_TIMESTAMP_AT_WHICH_ORDER_PLACED = 'SET_TIMESTAMP_AT_WHICH_ORDER_PLACED'


export const SET_FOOTER_COLOR = 'SET_FOOTER_COLOR'
